vich_uploader:
    db_driver: orm

    mappings:
        profile_image:
            uri_prefix: /images/profiles
            upload_destination: '%kernel.project_dir%/public/images/profiles'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

        student_image:
            uri_prefix: /images/students
            upload_destination: '%kernel.project_dir%/public/images/students'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
